# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

bioc_required: true

cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
