# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-devel

bioc_required: true

cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: docs
  on:
    branch: master
